Quadratic.class: Quadratic.java
	javac Quadratic.java
Quadratic: Quadratic.class
	java Quadratic

STDIN.class: STDIN.java
	javac STDIN.java --enable-preview --release=13
STDIN: STDIN.class
	java --enable-preview STDIN

.PHONY:
	Quadratic
	STDIN
