// @filename ampSurplusBookmarklet.min2.js
// @author Cole Gannon <chungannoncole@fhda.edu>
// @date 9 August 2023
// final bookmarklets
javascript:void((A=alert,u="User Error: ",V=(x,n)=>A(u+`"${x}" is not a valid ${n}!`),d=1,e="FHDA_Asset_Number f03_0000 Description Serial_Num/VIN Make/Manufacturer Model Model_Year f03_0001 Condition Code_for_Screen_Size_and_Item".split` `.map((e,i)=>(d&=(e=document.getElementById(e))instanceof(i>7?HTMLSelectElement:HTMLInputElement),e)),s=(i,v)=>(e[i].value=v,e[i].dispatchEvent(new FocusEvent("blur")),setTimeout(_=>e[i].value==v||(e[i].style.backgroundColor="#f35"),777),e[i].style.backgroundColor="#9da"),o=(i,t,o=[...e[i].children].find(o=>o instanceof HTMLOptionElement&&o.innerText==t))=>o&&s(i,o.value),r,l)=>d?(r=prompt`Paste the entire Excel row here starting with 1 ...`?.split("\t"))?(d=r.length)>14?/\d+/.test(d=r[2])?/\d{4}/.test(d=r[11])?(s(0,r[2]),s(1,r[3]),s(2,r[5]),s(3,r[8]),s(4,r[9]),s(5,r[10]),s(6,r[11]),s(7,r[13]),o(8,l=r[7]))?o(9,d=r[14])||V(d,"screen size"):V(d,"condition"):V(d,"Model Year"):V(d,"FHDA Asset Number"):A(u+"Missing Cells! Wanted 15, got "+d):A(u+"Blank Entry!"):A`Bookmarklet Failure! Are you on the right page?`)()

javascript:void((A=alert,u="User Error: ",V=(x,n)=>A(u+`"${x}" is not a valid ${n}!`),d=1,e="FHDA_Asset_Number f03_0000 Description Serial_Num/VIN Make/Manufacturer Model Model_Year f03_0001 Condition Code_for_Screen_Size_and_Item".split` `.map((e,i)=>(d&=(e=document.getElementById(e))instanceof(i>7?HTMLSelectElement:HTMLInputElement),e)),s=(i,v)=>(e[i].value=v,e[i].dispatchEvent(new FocusEvent("blur")),setTimeout(_=>e[i].value==v||(e[i].style.backgroundColor="#f35"),777),e[i].style.backgroundColor="#9da"),o=(i,t,o=[...e[i].children].find(o=>o instanceof HTMLOptionElement&&o.innerText==t))=>o&&s(i,o.value),r,l)=>d?(r=prompt`Paste the entire Excel row here starting with 1 ...`?.split("\t"))?(d=r.length)>14?/\d+/.test(d=r[2])?/\d{4}/.test(d=r[11])?([2,3,5,8,9,10,11,13].map((a,b)=>s(b,r[a])),o(8,d=r[7]))?o(9,d=r[14])||V(d,"screen size"):V(d,"condition"):V(d,"Model Year"):V(d,"FHDA Asset Number"):A(u+"Missing Cells! Wanted 15, got "+d):A(u+"Blank Entry!"):A`Bookmarklet Failure! Are you on the right page?`)()

javascript:void((A=alert,U="User Error: ",V=(x,n)=>A(U+`"${x}" is not a valid ${n}!`),D=1,E="FHDA_Asset_Number f03_0000 Description Serial_Num/VIN Make/Manufacturer Model Model_Year f03_0001 Condition Code_for_Screen_Size_and_Item".split` `.map((e,i)=>(D&=(e=document.getElementById(e))instanceof(i>7?HTMLSelectElement:HTMLInputElement),e)),S=(i,v,e=E[i])=>(e.value=v,e.dispatchEvent(new FocusEvent("blur")),setTimeout(_=>e.value==v||(e.style.backgroundColor="#f35"),777),e.style.backgroundColor="#9da"),O=(i,t,o=[...E[i].children].find(o=>o instanceof HTMLOptionElement&&o.innerText==t))=>o&&S(i,o.value),R,L)=>D?(R=prompt`Paste the entire Excel row here starting with 1 ...`?.split("\t"))?(D=R.length)>14?/\d+/.test(D=R[2])?/\d{4}/.test(D=R[11])?([2,3,5,8,9,10,11,13].map((c,i)=>S(i,R[c])),O(8,D=R[7]))?O(9,D=R[14])||V(D,"screen size"):V(D,"condition"):V(D,"Model Year"):V(D,"FHDA Asset Number"):A(U+"Missing Cells! Wanted 15, got "+D):A(U+"Blank Entry!"):A`Bookmarklet Failure! Are you on the right page?`)()

// V should just use D instead of having a param V(D,...)
// this also means we can call it using a tagged template
javascript:void((A=alert,U="User Error: ",D=1,V=n=>A(U+`"${D}" is not a valid ${n}!`),E="FHDA_Asset_Number f03_0000 Description Serial_Num/VIN Make/Manufacturer Model Model_Year f03_0001 Condition Code_for_Screen_Size_and_Item".split` `.map((e,i)=>(D&=(e=document.getElementById(e))instanceof(i>7?HTMLSelectElement:HTMLInputElement),e)),S=(i,v,e=E[i],s=s=>e.style.backgroundColor=s)=>(e.value=v,e.dispatchEvent(new FocusEvent("blur")),setTimeout(_=>e.value==v||s("#f35"),777),s("#9da")),O=(i,t,o=[...E[i].children].find(o=>o instanceof HTMLOptionElement&&o.innerText==t))=>o&&S(i,o.value),R,L)=>D?(R=prompt`Paste the entire Excel row here starting with 1 ...`?.split("\t"))?(D=R.length)>14?/\d+/.test(D=R[2])?/\d{4}/.test(D=R[11])?([2,3,5,8,9,10,11,13].map((c,i)=>S(i,R[c])),O(8,L=R[7]))?O(9,D=R[14])||V`screen size`:V`condition`:V`Model Year`:V`FHDA Asset Number`:A(U+"Missing Cells! Wanted 15, got "+D):A(U+"Blank Entry!"):A`Bookmarklet Failure! Are you on the right page?`)()

// changed O signature
javascript:void((A=alert,U="User Error: ",D=1,V=n=>A(U+`"${D}" is not a valid ${n}!`),E="FHDA_Asset_Number f03_0000 Description Serial_Num/VIN Make/Manufacturer Model Model_Year f03_0001 Condition Code_for_Screen_Size_and_Item".split` `.map((e,i)=>(D&=(e=document.getElementById(e))instanceof(i>7?HTMLSelectElement:HTMLInputElement),e)),S=(i,v,e=E[i],s=s=>e.style.backgroundColor=s)=>(e.value=v,e.dispatchEvent(new FocusEvent("blur")),setTimeout(_=>e.value==v||s("#f35"),777),s("#9da")),O=(i,t,o=[...E[i].children].find(o=>o instanceof HTMLOptionElement&&o.innerText==(D=R[t])))=>o&&S(i,o.value),R,L)=>D?(R=prompt`Paste the entire Excel row here starting with 1 ...`?.split("\t"))?(D=R.length)>14?/\d+/.test(D=R[2])?/\d{4}/.test(D=R[11])?([2,3,5,8,9,10,11,13].map((c,i)=>S(i,R[c])),O(8,7))?O(9,14)||V`screen size`:V`condition`:V`Model Year`:V`FHDA Asset Number`:A(U+"Missing Cells! Wanted 15, got "+D):A(U+"Blank Entry!"):A`Bookmarklet Failure! Are you on the right page?`)()
